dofile('Courseplay_FS22/scripts/CpObject.lua')
dofile('Courseplay_FS22/scripts/CpUtil.lua')
dofile('Courseplay_FS22/scripts/util/CpMathUtil.lua')
dofile('Courseplay_FS22/scripts/pathfinder/AnalyticSolution.lua')
dofile('Courseplay_FS22/scripts/pathfinder/State3D.lua')
dofile('Courseplay_FS22/scripts/pathfinder/Dubins.lua')

dofile('CourseGenerator/CourseGenerator.lua')
dofile('CourseGenerator/Logger.lua')
dofile('CourseGenerator/Util.lua')

dofile('CourseGenerator/geometry/Vector.lua')
dofile('CourseGenerator/geometry/Vertex.lua')
dofile('CourseGenerator/geometry/WrapAroundIndex.lua')
dofile('CourseGenerator/geometry/LineSegment.lua')
dofile('CourseGenerator/geometry/Polyline.lua')
dofile('CourseGenerator/geometry/Polygon.lua')
dofile('CourseGenerator/geometry/Intersection.lua')
dofile('CourseGenerator/geometry/Slider.lua')
dofile('CourseGenerator/geometry/Offset.lua')

dofile('CourseGenerator/Math.lua')
dofile('CourseGenerator/WaypointAttributes.lua')
dofile('CourseGenerator/Field.lua')
dofile('CourseGenerator/Row.lua')
dofile('CourseGenerator/RowPattern.lua')
dofile('CourseGenerator/Block.lua')
dofile('CourseGenerator/Headland.lua')
dofile('CourseGenerator/Center.lua')
dofile('CourseGenerator/FieldworkContext.lua')
dofile('CourseGenerator/FieldworkCourse.lua')
dofile('CourseGenerator/Island.lua')
dofile('CourseGenerator/SplineHelper.lua')
dofile('CourseGenerator/AnalyticHelper.lua')

dofile('AdjustableParameter.lua')
dofile('ToggleParameter.lua')
dofile('ListParameter.lua')