dofile('Courseplay_FS22/scripts/CpObject.lua')
dofile('Courseplay_FS22/scripts/CpUtil.lua')
dofile('Courseplay_FS22/scripts/util/CpMathUtil.lua')
dofile('Courseplay_FS22/scripts/pathfinder/AnalyticSolution.lua')
dofile('Courseplay_FS22/scripts/pathfinder/State3D.lua')
dofile('Courseplay_FS22/scripts/pathfinder/Dubins.lua')

dofile('CourseGenerator/CourseGenerator.lua')
dofile('CourseGenerator/CourseGeneratorClass.lua')
dofile('CourseGenerator/Math.lua')
dofile('CourseGenerator/Vector.lua')
dofile('CourseGenerator/Vertex.lua')
dofile('CourseGenerator/LineSegment.lua')
dofile('CourseGenerator/Polyline.lua')
dofile('CourseGenerator/Polygon.lua')
dofile('CourseGenerator/Slider.lua')
dofile('CourseGenerator/Field.lua')
dofile('CourseGenerator/Headland.lua')
dofile('CourseGenerator/FieldworkCourse.lua')

dofile('AdjustableParameter.lua')
dofile('ToggleParameter.lua')