lu = require("luaunit")
package.path = package.path .. ";../?.lua;..?.lua;../../Courseplay_FS22/scripts/?.lua"
require('CourseGenerator')
require('CpObject')
require('Math')
require('Vector')
require('LineSegment')
require('Polyline')
require('Polygon')
require('Field')
require('Headland')
