# The workflow name
name: Run unit tests

on: 
  push:
    paths:
      - '**.lua'
  pull_request:
    paths:
      - '**.lua'
  workflow_dispatch:

# The list of jobs this workflow executes
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Checkout Courseplay repository
        uses: actions/checkout@v3
        with:
          repository: Courseplay/Courseplay_FS22
          path: Courseplay_FS22
      - name: Setup Lua
        uses: xpol/setup-lua@v1
      - name: Run unit tests
        run: |
          cd CourseGenerator/test
          lua LineSegmentTest.lua
          lua TransformTest.lua
          lua PolylineTest.lua
          lua PolygonTest.lua
          lua FieldTest.lua
